atom-minimap/minimap

stylesheets/minimap.less

When selecting text in a notification, you can end up selecting the minimap as well.

Prevent selections on the minimap

---

lib/main.coffee

Hi, 
I have a "retina" screen mac and wanted to make use of the smaller real pixels; currently I have 1 real pixel interline, 3 real pixels char height, and 2 real pixels char width. I also experimented with smaller sizes, but my poor eyesight disagreed. 
Anyway, to do that, I needed the character sizes to be fractional – with a devicePixelRatio of 2, I want to use increments of .5. Hence my patch, and hence this pull request.

allow fractional sizes in minimap

---

lib/minimap-element.coffee
spec/helpers/events.coffee
spec/minimap-element-spec.coffee

Prerequisite for #290. 
This only covers the middle click equivalent to clicking on the minimap (point 1 in the original comment of #290). Dragging is not yet implemented. 
In the current implementation, middle clicking (even on this "visibleArea") centers the visible area to that destination. This may or may not prove awkward after dragging is implemented. I thought it would be more consistent this way. However, it looks like most scroll bar implementations behave the same way if they're left clicked or middle clicked (if started dragging from the bar itself), so I may revisit this while implementing dragging.

Implemented middle click to jump-to-location

---

lib/main.coffee
spec/minimap-main-spec.coffee

`standAloneMinimapForEditor` uses active editor only, which is trouble for package consumers that cycle through all editors.

Use provided editor in standAloneMinimapForEditor

---

lib/minimap-element.coffee
spec/helpers/workspace.coffee
spec/minimap-element-spec.coffee
spec/minimap-main-spec.coffee
spec/minimap-spec.coffee
styles/minimap.less

Includes: 
- A change in the way the minimap interact with the text editor in the flex layout (might help for #394 and #399). Chrome 45's flex model is slightly different than previous version, more accurate, which allowed me to get rid of the ugly margin right hack. Instead the size of the minimap is now resolved using `flex-basis`.
- An update of the tests suite to take the change in the flex box behaviour into account. That means that most measurements might not gives the same result on stable (so Travis should fail).
- An update of the test environment to match the recent change in Atom (`new TextEditor` being deprecated, for instance).
- The tests no longer use CSS transforms, as a nasty bug in Chrome 45 (at least) prevents the use of a `WebKitCSSMatrix` to compute the real offset of …

Fix minimap on latest beta (1.2.0)

---

lib/config-schema.json
lib/minimap-element.js
lib/minimap.js
lib/mixins/canvas-drawer.js
spec/minimap-element-spec.js
spec/minimap-spec.js

@abe33 
Should it need an option for `preventDevicePixelRatioRounding`?

add Minimap#getDevicePixelRatio and flooring the devicePixelRatio

---

lib/canvas-layer.js
lib/minimap-element.js
lib/minimap.js
lib/mixins/canvas-drawer.js
lib/mixins/decoration-management.js
spec/canvas-layer-spec.js
spec/minimap-element-spec.js
spec/minimap-spec.js

The main point of this optimisation is to avoid rendering the line tokens whenever a decoration is added, removed or changed. The various profiling I made in the past weeks all led to the `line.tokens` getter being too costly.
So now, decorations are rendered on two layers (back and front) and line tokens on the last one.
In the process I found a bug in the intact ranges computation that was making any change on a single line repainting the whole minimap below that line.

Separate tokens and decorations into different layers

---

lib/minimap-element.js
spec/helpers/events.js
spec/minimap-element-spec.js

TouchEvents and MouseEvents have a different interface, which leads to
incorrect processing of touch scrolling on the minimap.
Mapping both event types to a unified interface resolves this issue.

Fixes #383 Fix touch scroll support

---

styles/minimap.less

When the minimap is on right with absolute-mode the settings icon is  kind of blocked by the atom scrollbar.

Update settings icon position

---

lib/adapters/legacy-adapter.js
lib/minimap.js
lib/mixins/canvas-drawer.js
lib/mixins/decoration-management.js
spec/minimap-element-spec.js
spec/minimap-spec.js

These changes are an attempt at switching to the new `DisplayLayer` text decoration facilities (in a backward compatible manner), which have superseded some deprecated APIs, such as `tokenizedLineForScreenRow`. More informations in the [related PR](https://github.com/atom/atom/pull/11414).
@abe33: what do you think? I haven't tested this extensively, but definitely feel free to make any change you think would be needed to this branch (it's a fork, so I have given you collaborator access on my version of the repository).
Thanks! 🙇

Start using new DisplayLayer APIs

---

README.md

Caused by #498 
When copy+pasting it in my stylesheet there was an error.
````
Line number: 50
missing opening `{`
````

Fix closing bracets

---

README.md

[ci skip]
Just an extra line on the README

:memo: Add link to the quick-highlight integration

---

lib/adapters/stable-adapter.js

If component is not defined, then the error found in https://github.com/atom-minimap/minimap/issues/489#issuecomment-273715210 will happen. This way we prevent that.
Fix #489

:ambulance: Fix #489

---

lib/minimap.js
package.json

This PR introduces a change which causes `textEditor.onDidChange()` events to be dispatched at certain intervals instead of immediately. The delay is controlled by a new configuration option, `Redraw delay`.
When working with large files, causing the minimap to redraw itself after each keystroke brings Atom down to its kneels and drops the viewport's refresh rate to about 10fps. By grouping the change events and firing them only after certain interval, we can significantly increase performance and the editor's responsiveness back to normal.
Below you may find a performance timeline which compares Atom's performance before and after this change.
> Redraw minimap on each keystroke
> Redraw minimap only once per second
The framerate is **way** higher and the execution stacks after each …

Implement minimap redraw delay

---

lib/minimap-element.js
package.json
spec/minimap-element-spec.js

As discussed on Slack, `atom.views.pollDocument` is going to be removed from `ViewRegistry` soon because of its inefficiency. This pull request takes advantage of `resize-detector` and the new `IntersectionObserver` API to detect changes in the minimap element when `atom.views.pollDocument` can't be found.
/cc: @abe33

Use IntersectionObserver and resize-detector when possible

---

lib/main.js

Fixes #605
---
This is because a deactivate sets `this.editorsMinimaps` to `undefined` but plugins still have a reference to this package instance.

Guard against service usage after package is disabled in the same Atom session

---

lib/minimap-element.js
styles/minimap.less

Atom 1.19.0 broke the minimap on the left side #623. Furthermore there was an issue about depreciated selectors #613. This is a quick fix which I think solves both of those issue. 
I'm quite new to JS, so please let me know if there are any improvements I can make. Feel free also to simply use my PR as inspiration for a better fix.
Best.

Fix left side minimap depreciation

---

lib/minimap.js

Way back in https://github.com/atom/atom/commit/117a3fb1b57465e3164c378219eefcca4b5c22a5 (released in Atom v1.9.0-beta0) Atom introduced an experimental TextEditor::onDidTokenize method in order to subscribe to that event. Switch to using this instead of grabbing it through the private properties which no longer work as of [Atom v1.25.0-beta0](https://github.com/atom/atom/releases/tag/v1.25.0-beta0).
Note that this is still present in the [current codebase](https://github.com/atom/atom/blob/b9e4febf03f29ab4327b3b64d528cfbcbd6fb9b5/src/text-editor.js#L3631).
Fixes #649.

Use proper method to subscribe to onDidTokenize

---

README.md

urls cannot contain unencoded spaces

fix(README): broken link

---

README.md

Rather than merely visually hiding the scrollbar (you are still able to still click on it even if it is invisible), this change means that the scrollbar is actually not there.

Improve 'hiding scrollbars' tweak

---

lib/adapters/stable-adapter.js
styles/minimap.less

This is a UX improvement to show the `default` cursor instead of the `text` one.
With the `text` cursor looked like it was possible to select text on the minimap or the text back it if using the absolute mode.
Edit: I added a commit to be able to pass the builds.

default-cursor: Use default cursor for atom-text-editr-minimap

---

lib/minimap-element.js

Marking event listeners as passive, indicates that the callback will never call `event.preventDefault()`. This can improve scolling performance in many cases.
For more information on passive event listeners see: https://developers.google.com/web/updates/2016/06/passive-event-listeners

Make event listeners passive

---

lib/canvas-layer.js

Fix error when the middle pane is 0 width
Fixes https://github.com/atom-ide-community/minimap-plus/issues/15
Fixes https://github.com/atom-minimap/minimap/issues/702
Originally posted at https://github.com/atom-ide-community/minimap-plus/pull/13#issue-465109156 by @UziTech

fix: prevent error when minimap squashed

---

lib/mixins/canvas-drawer.js
package.json

This will prevent the very long lines to break minimap when softwrap is not enabled.
Originally posted at https://github.com/atom-ide-community/minimap-plus/commit/4df465572cc7c58f5032d54bcd262119ae574898

feat: limit the number of tokens that are rendered for one line

---

styles/minimap.less

css containment to improve performance
this means the css properties of the minimap does not affect other parts of Atom
https://drafts.csswg.org/css-contain/#propdef-contain
Originally posted at https://github.com/atom-ide-community/minimap-plus/pull/16

feat: add css containment to minimap elements

---

lib/minimap.js
package.json
spec/minimap-spec.js

This allows skipping the frames if the browser is busy doing other things, and it will improve the overall experience
References:
https://blog.teamtreehouse.com/efficient-animations-with-requestanimationframe
Originally posted at https://github.com/atom-ide-community/minimap-plus/pull/12

feat: use requestAnimationFrame to scheduleChanges 

---

lib/minimap-element.js
lib/minimap-quick-settings-element.js

Marking event listeners as passive, indicates that the callback will never call `event.preventDefault()`. This can greatly improve scrolling performance. 
This removes multiple warning in the dev console:
```
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```
For more information on passive event listeners see: https://developers.google.com/web/updates/2016/06/passive-event-listeners
:warning: This PR requires https://github.com/abe33/atom-utils/pull/3 to work correctly.

Mark atom-utils event listeners as passive

---

styles/minimap.less

Fixes #723 
The color and width of the scroll indicator make it almost invisible (especially for people with low sight or color blindness). 
Before this PR, I could not see this scroll indicator until I hacked its color in the dev editor, and I finally noticed that this scroll indicator is actually a thing!
I think we can still improve the scroll indicator:
- Currently, it is only shown if the minimap is longer than the height of the editor.
Normal:
Absolute mode:

fix: make scroll indicator more visible

---

lib/canvas-layer.js

we should fall back to the traditional canvas for the operating systems that do not support low-latency rendering.
https://developers.google.com/web/updates/2019/05/desynchronized#feature_detection
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext
Fixes #724

fix: disable desynchronized canvas on Linux

---

README.md

I emailed an employee at kite and he said that he couldn't find anyone at the company who knew anything about minimap so I'm pretty sure we can remove the sponsorship statement.

chore: remove kite sponsor link

---

styles/minimap.less

This adds contain_all to almost all selectors (the remaining ones that I thought will not need it). I am not sure if these remaining ones have a performance benefit.

fix: add more css containment (to all selectors)

---

lib/main.js
lib/minimap-element.js
lib/mixins/canvas-drawer.js
lib/mixins/decoration-management.js
lib/plugin-management.js
spec/minimap-element-spec.js

This prevents defining temporary strings that should resize to get a final string value.
```
git clone https://github.com/cpojer/js-codemod.git
jscodeshift -t js-codemod/transforms/template-literals.js lib
jscodeshift -t js-codemod/transforms/template-literals.js spec
jscodeshift -t js-codemod/transforms/object-shorthand.js lib
jscodeshift -t js-codemod/transforms/object-shorthand.js spec
```

fix: use strings interpolation instead of + and shorter version of object props

---

lib/minimap-element.js
lib/minimap.js
lib/mixins/canvas-drawer.js
spec/minimap-element-spec.js

Moved the independent changes from #744 to this PR

Free up free functions in CanvasDrawer

---

lib/main.js
lib/performance-monitor.js

The performance of Minimap with and without Tree-sitter is like night and day. We should inform the users about this, so they can have the best experience with Minimap.

feat: warn about poor performance if treesitter is off

---

lib/dom-styles-reader.js
lib/main.js
lib/minimap-element.js
lib/mixins/canvas-drawer.js
spec/minimap-element-spec.js

Minimap attaches a hidden dummy node into the editor, and render the elements with that scope, and then get the color property of the css. The speed is quite good (because the dummy node is hidden), but this is done for each token in the editor. To speed up this, there is a cache that stores the colors. 
This PR shares the cache between the editors so less rendering happens.
The benchmarks are available in this commit: 
https://github.com/atom-minimap/minimap/commit/6504a666926e3dacdc9441d737851aa90ff3d885
Running the benchmark shows that getting the token colors for the first time from an unknown language might take 10-30ms depending on the file size. But the subsequent calls only take 1-2ms maximum.

feat: reuse domStylesReader between editors

---

.terserrc.js
lib/decoration-management.js
lib/deps/underscore-plus.js
lib/minimap-plugin-generator-element.js
lib/mixins/canvas-drawer.js
package.json

Underscore-plus removed and replaced with custom functions implemented:
- The functions are more optimized
- This also reduces the bundle size from 120KB to 97KB.
Terser top-level is off because of this: https://github.com/terser/terser/issues/907

Optimizations

---

lib/mixins/canvas-drawer.js

Use property destructure instead of property accessing in decorations drawers. This allows eventually removing the need for passing an object (renderData) in later PRs.

fix: destructure renderData in decoration drawers

---

lib/decoration-management.js
lib/main.js
lib/minimap-element.js
lib/minimap-quick-settings-element.js
lib/minimap.js

- When minimap is toggled on/off and editors are closed/open, some null bugs may appear.
- The minimaps were not destroyed correctly
- hack for forcing scroller movement once minimap is toggled off
Fixes https://github.com/atom-minimap/minimap/issues/764
Fixes https://github.com/atom-minimap/minimap/issues/763

fix: toggle null-bugs

---

lib/main.js
lib/minimap-element.js
lib/minimap.js
spec/minimap-main-spec.js

Do not null set the properties manually. JavaScript's garbage collector is smart enough to collect the unreferenced destroyed variables.
Fixes #778

fix: do not null set the values in destroy

---

lib/minimap.js

Because `onMouseWheel` is a passive event listener we should not call `preventDefault`. Without this change, the code actually throws an exception!
I have tested the functionality without this code and it works as expected.
Enable independent scroll on minimap and try to scroll your mouse wheel while hovering on Minimap

fix: remove preventDefault from onMouseWheel for independent scroll

---

.github/workflows/CI.yml
lib/dom-styles-reader.js

Just a minor regexp fix in hueRegexp.
Issue: Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of filter.match #671

fix: rotateHue accepts negative hue values in DOMStylesReader

---

babel.config.json
lib/decoration.js
lib/minimap.js
package.json
pnpm-lock.yaml
rollup.config.js

fix: make the old decorations API type-safe

---

lib/minimap.js

Previously there was problem if scroll past end enabled.
No scroll past end - all is well.
Enabled - there's some offset between mouse on screen on minimap and actual screen.
Screencast: https://youtu.be/zfAk14_9CEQ
This should fix it.
I checked by console.log when scrolling, mouse position was bigger when scrolling to bottom then height of minimap.
So it didn't account space added if scroll past end enabled.
"Minimap.getHeight" should return total height of minimap (is this true ?) (I read it in method description), so this PR also accounts space after last line added if scroll past end enabled.

fix(lib.minimap):  scroll by drag if scrollPastEnd
