atom-minimap/minimap

lib/minimap-view.coffee
See https://github.com/fundon/atom-minimap/issues/229
=> Adjust height to match editor height

lib/main.coffee, lib/minimap-element.coffee, spec/minimap-element-spec.coffee
Hi, I just add scroll animation by using jQuery.animate, and leave it disabled by default. I wish you will like it, thanks.
=> Add scroll animation.

lib/main.coffee, lib/minimap-element.coffee, package.json, spec/minimap-element-spec.coffee
=> Fix toggle, disable/enable 

lib/mixins/canvas-drawer.coffee, lib/mixins/decoration-management.coffee, spec/minimap-element-spec.coffee
It works like a highlight but only render an outline of 1px around the marker range.
=> Add a highlight-outline decoration mode

lib/minimap-element.coffee, spec/minimap-element-spec.coffee
=> :bug: Fix not update when user-styles reload, #303

lib/minimap-element.coffee
[![Gyazo](http://i.gyazo.com/36ce9286db7753bbc39f9844a0d81fc5.gif)](http://gyazo.com/36ce9286db7753bbc39f9844a0d81fc5)
[![Gyazo](http://i.gyazo.com/c5e3f507e35433aa603ea800f79ce967.png)](http://gyazo.com/c5e3f507e35433aa603ea800f79ce967)
[![Gyazo](http://i.gyazo.com/e92d07682ec9a0e22b4114a0e889f9ad.png)](http://gyazo.com/e92d07682ec9a0e22b4114a0e889f9ad)
=> Fix leak minimap

CONTRIBUTING.md
Outdated link resolved to Atom flight manual
=> Update Atom contribution guidelines link

.travis.yml
Faster and Container based Builds!
=> update to latest Travis CI test script

.travis.yml
Jay, all builds are passing! :smiley:
=> run successful CI build

README.md
Added under the 'Tweaking The Minimap' main topic. I don't feel it's worth adding any screenshot but let me know if you want one.
=> Making Minimap only visible in the focused pane

styles/minimap.less
Not sure about the impact of this, but I encountered it when digging around in the developer tools
=> Fix incorrect value for display style

.travis.yml, CHANGELOG.md, README.md, lib/adapters/legacy-adapter.js, lib/adapters/stable-adapter.js, lib/canvas-layer.js, lib/decoration.js, lib/decorators/element.js, lib/decorators/include.js, lib/main.js, lib/minimap-element.js, lib/minimap-plugin-generator-element.js, lib/minimap-quick-settings-element.js, lib/minimap.js, lib/mixins/canvas-drawer.js, lib/mixins/decoration-management.js, lib/mixins/dom-styles-reader.js, lib/mixins/plugin-management.js, package.json, spec/canvas-layer-spec.js, spec/helpers/events.js, spec/helpers/workspace.js, spec/minimap-element-spec.js, spec/minimap-main-spec.js, spec/minimap-spec.js, styles/minimap.less
Needs Atom 1.13 to reach at least beta before considering merging
=> Remove shadow dom

lib/adapters/stable-adapter.js
=> Guard against there being no visible screen row

lib/adapters/stable-adapter.js, spec/minimap-spec.js
=> Various fixes

.github/workflows/CI.yml, CHANGELOG.md, package.json, spec/minimap-element-spec.js
=> Update Tests and CI

lib/adapters/legacy-adapter.js, lib/decoration.js, lib/decorators/element.js, lib/decorators/include.js, lib/main.js, lib/minimap-element.js, lib/minimap-plugin-generator-element.js, lib/minimap-quick-settings-element.js, lib/minimap.js, lib/mixins/canvas-drawer.js, lib/mixins/decoration-management.js, lib/mixins/dom-styles-reader.js, lib/mixins/plugin-management.js, package.json, spec/canvas-layer-spec.js, spec/helpers/events.js, spec/helpers/workspace.js, spec/minimap-element-spec.js, spec/minimap-main-spec.js, spec/minimap-spec.js
Originally posted at https://github.com/atom-ide-community/minimap-plus/pull/10
- Bumps all the dependencies
- This includes the bumping standard for linting. I have run `npm run lint` to fix all the linting issues.
=> fix: bump dependencies

lib/minimap-element.js, package.json, spec/minimap-element-spec.js
Originally posted at https://github.com/atom-ide-community/minimap-plus/commit/5c1c3a6e257fbdac8c006e1af2e3ac964439b558
=> feat: use optimal settings as the default

lib/canvas-layer.js
A new feature in Electron 6
https://developers.google.com/web/updates/2019/06/nic75#desync
Originally posted at https://github.com/atom-ide-community/minimap-plus/pull/17
=> feat: use desynchronized canvas

package.json
See https://github.com/atom-minimap/minimap/pull/729 for the rest...
=> fix: Rename "Auto Toggle" to "Show Minimap on Atom Start"

README.md
See https://github.com/atom-minimap/minimap/pull/728
=> chore(readme): update auto toggle docs

.terserrc.js, lib/minimap-element.js, package-lock.json, package.json, spec/minimap-element-spec.js
This PR includes various optimizations for MinimapElement class. See the commit list for each of them.
=> fix: optimizations in MinimapElement 

.terserrc.js, package.json
fix: remove spec-specific code in the production build
=> fix: remove spec specific code in production build

lib/mixins/decoration-management.js, spec/minimap-spec.js
Why Maps are faster:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
Why exact compares are faster: 
exact compare with undefined instead of truthy/null check is 12% faster
https://jsbench.me/q9kja8u4c2/2
Related to https://github.com/atom-minimap/minimap/issues/735
=> Decoration Management Optimizations

lib/minimap-element.js
https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener
https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/removeListener
https://stackoverflow.com/a/57928252/7910299
=> fix: mediaQuery deprecations

lib/minimap-plugin-generator-element.js, lib/mixins/canvas-drawer.js, lib/mixins/decoration-management.js, lib/mixins/dom-styles-reader.js
As already mentioned in [this comment](https://github.com/atom-minimap/minimap/pull/736#issuecomment-752145731), free functions are faster.
https://jsbench.me/g4kjcq9j3s
=> Free up free functions

lib/mixins/canvas-drawer.js, spec/minimap-element-spec.js
- This frees up a lot of the functions in CanvasDrawer.
- Takes the common logics out of the loop
- Improves the dispatching logic for decoration drawing
=> fix: more CanvasDrawer optimizations

lib/mixins/canvas-drawer.js
- Takes the constant/shared parts out of the hot loops of Minimap
- Inlines the code so the compiler can optimize it.
=> fix: updateCanvas optimizations

.terserrc.js, lib/main.js, package-lock.json, package.json, rollup.config.js
I want to explore using AssemblyScript. For that matter, I have added a rollup-plugin-assemblyscript to rollup-plugin-atomic. So, we should switch to Rollup.
=> chore: switch to Rollup

.github/workflows/CI.yml, lib/main.js, package.json
test linting in GitHub Actions without the `--fix` parameter
=> chore(ci): test linting without --fix in ci

lib/main.js, lib/minimap-element.js, lib/minimap.js
Fixes https://github.com/atom-minimap/minimap/issues/766
=> Fix strange null bugs

lib/main.js, spec/minimap-main-spec.js
fixes #780
fixes https://github.com/ansballard/minimap-autohider/issues/19
=> fix: view provider returns correct minimap element

lib/canvas-layer.js, lib/minimap-element.js, spec/minimap-element-spec.js, styles/minimap.less
fixes #782 
Removed hack for text editor margin and just changed flexbox order
=> fix: fix minimap on left width

lib/canvas-layer.js
=> fix: disable desynchronized canvas

lib/minimap.js, package.json, pnpm-lock.yaml, spec/minimap-spec.js
=> fix: getDevicePixelRatio will return 0 on Linux resulting in no minimap
